#!/usr/bin/env bash

#
# git-pull-all
#
# Runs a `git pull` in all of the repositories in the LearnersGuild org.
#

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${ROOT_DIR}/.env"

repos="${ROOT_DIR}/repos.txt"

cd $LG_BASE_DIR

while read repo; do
  cd "$LG_BASE_DIR/$repo"
  git pull
done <"$repos"
