#!/usr/bin/env bash

#
# git-pull-all
#
# Runs a `git pull` in all of the repositories in the LearnersGuild org.
#

set -e

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${ROOT_DIR}/.env"

repos="${ROOT_DIR}/repos.txt"

[[ -z $LG_BASE_DIR ]] && {
  echo "LG_BASE_DIR environment variable not found. Add to your .env file."
  exit 1
}

while read repo; do
  repo_dir="$LG_BASE_DIR/$repo"
  cd "$repo_dir"

  if git diff-index --quiet HEAD --
  then
    echo "> $repo -- Checking out and pulling to master"
    git checkout master
    git pull origin master
  else
    echo "> $repo -- Not pulling; you have unstaged changes"
  fi
done <"$repos"
