#!/usr/bin/env bash

#
# git-clone-all
#
# Clones all of the repositories in the LearnersGuild org into the LG_BASE_DIR
# directory (specified in ./.env).
#

set -e

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${ROOT_DIR}/.env"

repos="${ROOT_DIR}/repos.txt"

[[ -z $LG_BASE_DIR ]] && {
  echo "LG_BASE_DIR environment variable not found. Add to your .env file."
  exit 1
}

while read repo; do
  repo_dir="$LG_BASE_DIR/$repo"
  [ ! -d "$repo_dir" ] && {
    # Only attempt to clone if directory doesn't exist
    git_url="git@github.com:LearnersGuild/$repo.git"
    git clone $git_url $repo_dir
  }
done <"$repos"
